---
- name: Deploy Flask Application
  hosts: all
  become: yes
  vars:
    app_name: simple-flask-app
    app_dir: /var/www/simple-flask-app
    git_repo: https://github.com/AmgadAzzam/flask-app.git
    docker_image: amgadazzam/simple-flask-app-img:v1

  tasks:
    - name: Install Docker
      yum: 
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone application repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        update: yes

    - name: Build Docker image
      command: docker build -t "{{ docker_image }}" "{{ app_dir }}"

    - name: Run Docker container
      command: docker run -d -p 80:5000 "{{ docker_image }}"
